### ISSUE TITLE
Example42 feed contains wrong year

### ISSUE THREAD

**Issue by TraGicCode** [masterzen/planetpuppet#1]
Not sure if this is something specific with puppet planet but the example42 urls have the year 2019 instead of 2018 in them causing them all to 404 when a user clicks them.  I looked at the atom feed from example42 so i assume it's happening here or whatever thirdparty planetpuppet is using the parse the feeds.

/cc @tuxmea

**Comment by masterzen** [comment]
@TraGicCode thanks for reporting the issue. 
That's very strange as the feed is correct and previous articles have the correct date.
I'm looking at it.

**Comment by masterzen** [comment]
Apparently the feed had been containing invalid dates at some point, and the planet aggressively cached those entries. I've removed them and they are now properly sorted at the right position and link to the correct articles.

Thanks @TraGicCode!

**Comment by tuxmea** [comment]
Thanks for taking care. We had one posting in the past referencing the wrong year. Sorry for the mess.

**Comment by TraGicCode** [comment]
That was quick.  Thanks @masterzen for the quick turnaround and thanks @tuxmea for responding as well
